Feature/Biometrics
stytchauth/stytch-kotlin pull request #44
Opened 2022-11-29 14:27 UTC by jhaven-stytch

Linear Ticket:
[SDK-624](https://linear.app/stytch/issue/SDK-624)
[SDK-625](https://linear.app/stytch/issue/SDK-625)
[SDK-626](https://linear.app/stytch/issue/SDK-626)

## Changes:
1. Adds biometric SDK endpoints
2. Updates/adds tests
3. Updates demo app with biometric register/authorize examples
4. Updates demo app with a revokesession button

## Notes:
- There's a small chance that the key generation/fetching may change following a meeting with Latacora later today, but currently, it follows whats done in RN.

2022-12-02 18:52 UTC, jhaven-stytch commented
@dan-stytch this is ready for review now :)

2022-12-05 21:16 UTC, jhaven-stytch commented
@dan-stytch FYI after talking with @mary-stytch we decided to update this so the SDK handles the biometric prompt/callback handling, too (currently it expects the developer to implement that and _then_ call the SDK methods). So you can hold off on reviewing it for now :)

2022-12-06 15:38 UTC, jhaven-stytch commented
Ready... again 😅

2022-12-13 17:13 UTC, jhaven-stytch commented
Alright, third time's the charm: BouncyCastle implementation has been merged in, good to review :)

2022-12-13 22:11 UTC, dan-stytch approved these changes
A couple minor things and some questions, but overall lgtm!

2022-12-14 13:56 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/Biometrics.kt
> +     * @param allowFallbackToCleartext opts-in to potentially unsafe behavior
Yes, latacora wrote something up for us, it's linked in the tech doc context section! Spencer was gonna take a swing at editing it, and then we can share it however we need.

2022-12-14 13:56 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/Biometrics.kt
> +    /**
I have not. We should definitely talk about it!

2022-12-14 13:57 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/BiometricsImpl.kt
> +            userManagerApi.deleteBiometricRegistrationById(it)
Ooh, good call, I don't recall when the cached user object is updated, but I will look into that.

2022-12-14 13:57 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/BiometricsImpl.kt
> +                        storageHelper.saveValue(CIPHER_IV_KEY, cipher.iv.toBase64EncodedString())
Yes indeed.

2022-12-14 13:57 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/BiometricsProviderImpl.kt
> +            .setTitle("Biometric login")
On it.

2022-12-14 13:59 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/BiometricsProviderImpl.kt
> +                    "No biometrics currently enrolled on device. Starting biometrics enrollment flow."
It does, but I'm realizing this is not a great place to do it. We shouldn't be forcing the user into biometrics creation if the developer is just asking if biometrics are available. So I'm going to refactor this to expose an enum and the developer can choose to either kick off biometrics creation or not. Demo app will be updated to show that.

2022-12-14 13:59 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/EncryptionManager.kt
> +    private fun getOrGenerateNewAES256KeysetHandle(context: Context, keyAlias: String): AndroidKeysetManager {
yeah, a victim of our multi attempts at this, haha. Will fix.

2022-12-14 14:01 UTC, jhaven-stytch commented on sdk/src/test/java/com/stytch/sdk/network/StytchApiServiceTests.kt
> +            assert(body.contains("public_key\":\"publicKey\""))
After I saw that in your last PR I thought about doing something similar here. Will add it to our cleanup/improvements project in linear :)

2022-12-14 15:54 UTC, jhaven-stytch commented
@dan-stytch rerequesting review after making changes based on above

2022-12-14 18:59 UTC, dan-stytch requested changes
I think the deleteFactor change is probably worth making before merging, other stuff is just for clarification or pretty minor

2022-12-14 18:59 UTC, dan-stytch commented on sdk/src/main/java/com/stytch/sdk/UserManagementImpl.kt
> +            is StytchResult.Error -> null
I saw your commit message here, just curious what the main concerns are w.r.t. sessionStorage.user getting out of sync

2022-12-14 18:59 UTC, dan-stytch commented on sdk/src/main/java/com/stytch/sdk/UserManagementImpl.kt
> +        getUser()
This extra call shouldn't be necessary I don't believe, I think these deletion calls should actually return the same response as `getUser`, so you should be able to utilize the user object from that result and not need to wait for or rely on the extra call here

2022-12-14 18:59 UTC, dan-stytch commented on sdk/src/main/res/values/strings.xml
> +    <string name="stytch_biometric_prompt_subtitle">Authenticate using your biometric credential</string>
Very minor, but do you know if it's common on Android for a subtitle to have a period at the end? Wondering whether we should include one, but we can probably just use other prompts as guidance here

2022-12-14 19:19 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/UserManagementImpl.kt
> +        getUser()
Hmm, let me run them through proxyman to confirm. If they do, great, yeah, saves us a call. But these are currently defined as only returning a BaseResponse (no userdata), so all of those calls will need to be updated.

2022-12-14 19:25 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/UserManagementImpl.kt
> +            is StytchResult.Error -> null
My concern here was just unifying that anytime we fetch the user, we update the cached version, so we're not waiting on the background session updater job. And if a getUser call failed, then we probably don't want to keep the cached user, as something is probably wrong (ie: there is no authenticated user). Although I guess that could be problematic if it's a transient network issue instead of a failed user issue. But this check and setting will be unnecessary if your other comment is true and the delete responses contain a full user object, because we can leverage the existing session updater work that we do on other session-modifying calls.

2022-12-14 19:46 UTC, jhaven-stytch commented on sdk/src/main/java/com/stytch/sdk/UserManagementImpl.kt
> +        getUser()
Ok, it doesn't return session data, but it does return user data, and that's workable 🎉

2022-12-14 21:28 UTC, dan-stytch approved these changes
🚢 !

2022-12-15 14:41 UTC, merged